export const productLongDescriptions = {
  "en": {
    "Pricing Validation & Intelligence": [
      "PROBLEM",
      "Pricing decisions across e-retailers and marketplaces were highly fragmented and reactive.",
      "Retailer price data, competitor benchmarks and internal pricing logic were disconnected",
      "Pricing compliance (MSRP, margin thresholds) could not be consistently enforced",
      "Teams relied on manual Excel-based comparisons, leading to delays and errors",
      "Limited visibility created grey-market risks, price conflicts and margin leakage",
      "Decision-making was slow, inconsistent and not scalable across channels",
      "SOLUTION",
      "A unified AI-assisted pricing intelligence layer was developed, integrating internal and external data sources into a single decision system.",
      "Connected PIM data, retailer price feeds and competitor data",
      "Implemented AI-based product matching for normalized benchmarking",
      "Established pricing guardrails (MSRP, margin thresholds, channel strategy)",
      "Built a real-time validation and monitoring system instead of periodic checks",
      "Enabled margin-aware and competitive pricing decisions through centralized dashboards",
      "ACTION",
      "Designed and implemented the data architecture combining internal and external pricing signals",
      "Built automated pipelines to ingest and normalize retailer and competitor data",
      "Developed AI-assisted validation logic to flag pricing deviations and risks",
      "Created SKU-level benchmarking and pricing dashboards for real-time visibility",
      "Introduced decision workflows to replace manual reporting and accelerate execution",
      "Aligned Marketing, Sales and Commercial teams around a single pricing source of truth",
      "RESULT",
      "+11% Average Order Value (AOV) through optimized pricing strategies",
      "+12pp Buy Box Share via improved competitiveness and pricing consistency",
      "+14pp Contribution Margin by enforcing margin-aware pricing decisions",
      "+30% Pricing Compliance Rate with automated guardrail enforcement",
      "-40% Manual Pricing Effort by eliminating Excel-based workflows",
      "+50% Faster Decision-Making through real-time insights",
      "+25% Cross-channel Price Consistency improving brand and channel control"
    ],
    "BIODERMA 360 e-Prescription System": [
      "PROBLEM",
      "Healthcare and dermocosmetic journeys were fundamentally disconnected between prescription intent and actual purchase behavior.",
      "Doctors generated recommendations, but no measurable link existed between prescription and purchase",
      "Patient journeys were offline-first, fragmented and untrackable",
      "No visibility into prescription-to-conversion funnel performance",
      "CRM, e-commerce and pharmacy channels operated in silos",
      "Regulatory constraints (GDPR) limited the ability to track and optimize user behavior",
      "This resulted in:",
      "Lost conversion opportunities",
      "Inefficient marketing investments",
      "Zero feedback loop between medical recommendation and commercial outcome",
      "SOLUTION",
      "A fully integrated, GDPR-compliant 360° e-prescription ecosystem was designed to connect doctors, patients, pharmacies and digital channels into a single measurable journey.",
      "Built a dynamic prescription system generating personalized product recommendations",
      "Delivered prescriptions instantly to patients via NFC-triggered mobile flows",
      "Connected prescription output to e-commerce and pharmacy conversion journeys",
      "Enabled anonymized data capture to ensure full compliance with privacy regulations",
      "Created a closed-loop system linking medical intent to commercial performance",
      "ACTION",
      "Designed end-to-end digital prescription journey architecture (doctor → patient → purchase)",
      "Developed NFC-enabled prescription triggers to eliminate friction in access",
      "Built dynamic recommendation logic based on indication and product mapping",
      "Integrated system with e-commerce platforms and pharmacy flows",
      "Implemented anonymized tracking infrastructure for GDPR-compliant measurement",
      "Created 360° funnel dashboards to monitor prescription → engagement → conversion",
      "Aligned Medical, Marketing and Commercial teams around a shared performance model",
      "RESULT",
      "Prescription-to-purchase conversion: ~22% → ~34% (+12pp)",
      "Doctor adoption rate: +40%",
      "Pharmacy funnel completion: +25%",
      "Patient engagement rate: +30%",
      "Campaign conversion uplift: +15% through connected journeys",
      "Paper-based OPEX: -70% via digitalization",
      "Full-funnel visibility from prescription intent to final purchase",
      "This system fundamentally transformed prescription from a static medical recommendation into a measurable, optimizable growth engine.",
      "It established, for the first time, a data bridge between medical interaction and commercial performance, enabling:",
      "Smarter budget allocation",
      "Real-time journey optimization",
      "Stronger alignment between medical strategy and revenue outcomes",
      "Positioning BIODERMA not just as a product brand, but as a digitally-enabled healthcare ecosystem player."
    ],
    "BIODERMA AI-Driven Visit Planning Mobile Application": [
      "PROBLEM",
      "Field force visit planning was largely manual, static and not aligned with commercial value.",
      "Visit plans were based on habit, territory proximity or intuition, not data",
      "No structured way to prioritize high-value HCPs (CLV-based)",
      "Routes were inefficient, leading to time loss and suboptimal coverage",
      "Engagement history and potential were not fully integrated into planning",
      "Daily planning lacked real-time adaptability (traffic, cancellations, changes)",
      "This resulted in:",
      "Low field productivity",
      "Missed high-value opportunities",
      "Inefficient time allocation across accounts",
      "SOLUTION",
      "An AI-powered mobile visit planning and decision support system was developed to optimize field operations.",
      "Introduced CLV-based prioritization model to rank HCPs by value",
      "Built engagement scoring system combining behavioral and interaction data",
      "Integrated real-time traffic data to dynamically optimize routes",
      "Enabled intelligent calendar planning based on value, location and timing",
      "Delivered all insights through a mobile-first interface for field usability",
      "ACTION",
      "Designed and implemented CLV/LTV-based scoring models for HCP prioritization",
      "Developed engagement scoring logic incorporating visit history and interaction signals",
      "Built route optimization engine integrating real-time traffic and geo-data",
      "Created dynamic daily planning interface for mobile usage",
      "Integrated with CRM and data sources to ensure real-time data flow",
      "Replaced static planning with AI-assisted recommendation engine",
      "Trained field teams and embedded the system into daily workflows",
      "RESULT",
      "Field productivity: +25–30% through optimized visit planning",
      "High-value account coverage: +35% via CLV-based prioritization",
      "Route efficiency: +20% (reduced travel time & better sequencing)",
      "Visit effectiveness: +15–20% (better quality interactions)",
      "Planning time: -40% through automation",
      "Adoption rate (field teams): >80% due to mobile-first usability",
      "This solution transformed field operations from a static scheduling activity into a real-time, AI-driven decision system.",
      "It enabled a shift from:",
      "“Who is closest?” → “Who creates the most value?”",
      "“Where should I go?” → “What is the optimal commercial route today?”",
      "Ultimately positioning the field force as a data-driven growth engine, not just an execution layer."
    ],
    "BIODERMA Tasky AI Web Application": [
      "PROBLEM",
      "Cross-functional execution across Marketing, Sales, Medical and Commercial teams was fragmented and difficult to scale.",
      "Tasks were managed across emails, meetings and disconnected tools",
      "Limited visibility into who owns what, by when, and at what status",
      "Dependencies between teams created bottlenecks and delays",
      "No standardized workflow structure → inconsistent execution quality",
      "Lack of centralized tracking made performance and accountability unclear",
      "This resulted in:",
      "Coordination friction across teams",
      "Delayed project delivery",
      "Inefficient use of resources and time",
      "SOLUTION",
      "A centralized, AI-supported workflow and task management system was developed to standardize execution and improve cross-functional collaboration.",
      "Built a custom operating model inspired by tools like Wrike & Asana",
      "Established structured task flows, ownership and deadline tracking",
      "Enabled cross-team visibility across all ongoing projects",
      "Introduced AI-assisted prioritization and workflow guidance",
      "Created a scalable system aligned with organizational processes and governance",
      "ACTION",
      "Designed end-to-end workflow architecture across departments",
      "Built a custom web application using low-code technologies (Power Apps ecosystem)",
      "Defined standardized task structures (owner, deadline, status, dependencies)",
      "Implemented cross-functional project tracking dashboards",
      "Integrated workflows across Marketing, Sales and Medical teams",
      "Introduced notification and follow-up mechanisms to reduce delays",
      "Embedded system into daily operations through training and governance alignment",
      "RESULT",
      "Execution speed: +30–40% through reduced coordination friction",
      "Task visibility: +50% across teams and stakeholders",
      "On-time delivery rate: +25% via structured tracking",
      "Cross-functional alignment: +35% (reduced miscommunication & rework)",
      "Manual follow-up effort: -40% through automated tracking",
      "Operational efficiency: +20–25% across teams",
      "This solution transformed execution from a people-dependent coordination model into a system-driven operating model.",
      "It enabled a shift from:",
      "“Who is doing this?” → “It’s already tracked, visible and accountable”",
      "“What’s the status?” → “Everything is measurable in real-time”",
      "Positioning Tasky AI as a digital operating system layer that scales execution quality, speed and organizational discipline."
    ],
    "360? Real-Time Executive Dashboard and Forecast": [
      "PROBLEM",
      "Commercial and supply chain decisions were based on delayed, fragmented and backward-looking data.",
      "Sell-out data, inventory levels and campaign performance were not unified",
      "Reporting was lagging, making it impossible to react to demand shifts in real time",
      "Forecasting relied heavily on manual assumptions and static models",
      "Limited visibility into seasonality patterns and trend dynamics",
      "No single system to connect commercial performance with stock planning",
      "This resulted in:",
      "Stock imbalances (overstock / stock-outs)",
      "Missed revenue opportunities",
      "Reactive instead of proactive decision-making",
      "SOLUTION",
      "A centralized real-time executive decision layer was developed, combining analytics, forecasting and business intelligence into one system.",
      "Integrated sell-out signals, campaign data and inventory inputs",
      "Built predictive models using seasonality, historical trends and demand signals",
      "Enabled real-time monitoring of performance and demand shifts",
      "Created a unified executive dashboard layer for decision-making",
      "Connected commercial and supply chain perspectives into a single view",
      "ACTION",
      "Designed and implemented data pipelines aggregating multi-source inputs (sell-out, stock, media, CRM)",
      "Developed predictive forecasting models combining trend, seasonality and real-time signals",
      "Built Power BI dashboards for executive-level visibility and usability",
      "Created SKU-level and category-level performance tracking",
      "Implemented scenario planning capabilities for proactive decision-making",
      "Enabled real-time alerting and anomaly detection for demand shifts",
      "Aligned stakeholders (Commercial, Supply Chain, Marketing) around a single decision interface",
      "RESULT",
      "Forecast accuracy: +25–30% through predictive modeling",
      "Stock-out reduction: -20–25% via proactive planning",
      "Inventory efficiency: +15–20% (better stock allocation)",
      "Decision-making speed: +50% with real-time visibility",
      "Revenue opportunity capture: +10–15% through demand responsiveness",
      "Executive visibility: +100% (single source of truth across functions)",
      "This system transformed reporting from a passive analytics function into an active decision engine.",
      "It enabled a shift from:",
      "“What happened?” → “What will happen next?”",
      "“Let’s analyze later” → “Let’s act now”",
      "Positioning the dashboard not as a reporting tool, but as a real-time commercial control tower driving forecasting accuracy, inventory efficiency and business performance."
    ],
    "BIODERMA Invoice Automation System": [
      "PROBLEM",
      "Invoice processing was manual, repetitive and error-prone, creating inefficiencies in finance operations.",
      "Invoices arrived via email attachments in different formats (PDF, image, scan)",
      "Data extraction required manual reading and input into systems",
      "High risk of human error and inconsistencies",
      "No centralized structure for searching, tracking or validating invoices",
      "Significant time spent on low-value, repetitive tasks",
      "This resulted in:",
      "Operational bottlenecks in finance workflows",
      "Limited data reliability",
      "Low scalability as volume increased",
      "SOLUTION",
      "An automated invoice intake and processing workflow was developed using OCR and Power Automate.",
      "Extracted invoice data automatically from email attachments",
      "Applied OCR technology to read unstructured documents",
      "Consolidated validated data into a structured, centralized document layer",
      "Enabled searchable, trackable and standardized finance inputs",
      "Reduced dependency on manual handling and fragmented processes",
      "ACTION",
      "Designed and implemented Power Automate workflow architecture",
      "Integrated email ingestion triggers for automatic invoice detection",
      "Built OCR-based extraction pipeline for structured data capture",
      "Defined validation logic to ensure data accuracy and consistency",
      "Created centralized invoice repository / operational document layer",
      "Standardized data fields for finance and reporting usability",
      "Automated routing and handling to eliminate manual intervention",
      "RESULT",
      "Manual processing effort: -60–70% through automation",
      "Processing time per invoice: -50%",
      "Data accuracy: +25–30% via standardized extraction",
      "Operational workload: significantly reduced, freeing finance resources",
      "Searchability & traceability: +100% with centralized data structure",
      "Scalability: enabled without increasing headcount",
      "This system transformed invoice handling from a manual back-office task into a structured, automated data pipeline.",
      "It enabled a shift from:",
      "“Open, read, input” → “Auto-ingest, validate, store”",
      "“Where is this invoice?” → “Everything is searchable and structured”",
      "Positioning finance operations as a data-driven and automation-enabled function, not a manual processing layer."
    ],
    "BIODERMA PTA Challenge Web Application": [
      "PROBLEM",
      "Pharmacy sales activation campaigns were difficult to track, validate and scale.",
      "Sales participation was based on manual reporting or trust-based inputs",
      "No reliable way to verify actual product-level sales performance",
      "Limited visibility into who is performing, how much and how fast",
      "Incentive programs lacked transparency and real-time motivation",
      "Campaign tracking required manual consolidation and reconciliation",
      "This resulted in:",
      "Low engagement from pharmacy teams",
      "Inefficient campaign execution",
      "Limited ability to optimize incentive-driven sales performance",
      "SOLUTION",
      "A gamified web-based pharmacy challenge platform was developed, combining OCR-based sales validation with real-time leaderboard tracking.",
      "Enabled pharmacies to scan receipts and submit sales proof digitally",
      "Used OCR to extract BIODERMA product data, quantities and pricing",
      "Connected submissions to participant accounts and campaign logic",
      "Introduced real-time leaderboard system to drive competition and engagement",
      "Created a transparent, scalable system for incentive-based sales activation",
      "ACTION",
      "Designed end-to-end challenge and reward system architecture",
      "Built OCR pipeline to extract product-level data from receipt images",
      "Developed validation logic to ensure accuracy of submitted sales data",
      "Created user interface for pharmacies to upload and track submissions",
      "Implemented real-time leaderboard and scoring system",
      "Integrated campaign tracking for Marketing and Commercial teams",
      "Automated aggregation of sales data for performance monitoring and reporting",
      "RESULT",
      "Pharmacy engagement: +40–50% through gamified participation",
      "Sales activation performance: +20–30% uplift during campaign periods",
      "Data reliability: +30% via OCR-based validation",
      "Campaign tracking effort: -50% through automation",
      "Transparency: +100% with real-time leaderboard visibility",
      "Participation rate: significantly increased across pharmacy network",
      "This solution transformed incentive campaigns from a manual, opaque process into a real-time, data-driven engagement system.",
      "It enabled a shift from:",
      "“Report your sales” → “Prove and track it instantly”",
      "“Who is performing?” → “See it live on the leaderboard”",
      "Positioning the platform as a scalable sales activation engine, combining gamification, validation and performance visibility in one system."
    ]
  },
  "de": {
    "Pricing Validation & Intelligence": [
      "PROBLEM",
      "Die Preisgestaltung im Online-Handel und auf Marktplätzen war stark fragmentiert und reaktiv.",
      "Preisdaten von Einzelhändlern, Vergleichswerte von Wettbewerbern und interne Preislogik waren nicht miteinander verbunden.",
      "Die Einhaltung der Preisvorgaben (UVP, Margenschwellen) konnte nicht konsequent durchgesetzt werden.",
      "Die Teams verließen sich auf manuelle, Excel-basierte Vergleiche , was zu Verzögerungen und Fehlern führte.",
      "Die eingeschränkte Transparenz führte zu Risiken im Graumarkt, Preiskonflikten und Margenverlusten.",
      "Die Entscheidungsfindung war langsam, uneinheitlich und nicht kanalübergreifend skalierbar.",
      "LÖSUNG",
      "eine einheitliche , KI-gestützte Preisinformationsebene entwickelt, die interne und externe Datenquellen in ein einziges Entscheidungssystem integriert.",
      "Vernetzte PIM-Daten, Preisfeeds von Einzelhändlern und Wettbewerbsdaten",
      "Implementierte KI-basierte Produktabgleichung für normalisiertes Benchmarking",
      "Festgelegte Preisrichtlinien (UVP, Margenschwellen, Vertriebskanalstrategie)",
      "Anstelle periodischer Prüfungen wurde ein Echtzeit-Validierungs- und Überwachungssystem entwickelt.",
      "Ermöglichung margenorientierter und wettbewerbsfähiger Preisentscheidungen durch zentrale Dashboards",
      "AKTION",
      "Datenarchitektur, die interne und externe Preissignale kombiniert, wurde entworfen und implementiert.",
      "automatisierte Pipelines entwickelt , um Daten von Einzelhändlern und Wettbewerbern zu erfassen und zu normalisieren.",
      "Entwicklung einer KI-gestützten Validierungslogik zur Kennzeichnung von Preisabweichungen und Risiken",
      "Erstellung von SKU-basierten Benchmarking- und Preis-Dashboards für Echtzeit-Transparenz",
      "Es wurden Entscheidungsworkflows eingeführt , um die manuelle Berichterstattung zu ersetzen und die Ausführung zu beschleunigen.",
      "Ausgerichtete Marketing-, Vertriebs- und Geschäftsteams auf einer einzigen, verlässlichen Preisquelle",
      "ERGEBNIS",
      "+11 % durchschnittlicher Bestellwert (AOV) durch optimierte Preisstrategien",
      "+12 Prozentpunkte Marktanteil in der Buy Box durch verbesserte Wettbewerbsfähigkeit und Preiskonsistenz",
      "+14 Prozentpunkte Deckungsbeitrag durch die Umsetzung margenorientierter Preisentscheidungen",
      "+30 % höhere Einhaltungsquote der Preise durch automatisierte Leitplankenüberwachung",
      "-40 % manueller Preisgestaltungsaufwand durch Abschaffung Excel-basierter Arbeitsabläufe",
      "+50 % schnellere Entscheidungsfindung durch Echtzeit-Einblicke",
      "+25 % kanalübergreifende Preiskonsistenz zur Verbesserung der Marken- und Kanalkontrolle"
    ],
    "BIODERMA 360 e-Prescription System": [
      "PROBLEM",
      "Im Gesundheitswesen und im Bereich der Dermokosmetik bestanden grundsätzliche Diskrepanzen zwischen der Verschreibungsabsicht und dem tatsächlichen Kaufverhalten.",
      "Ärzte erstellten Empfehlungen, aber es bestand kein messbarer Zusammenhang zwischen Verschreibung und Kauf.",
      "Die Patientenprozesse waren zunächst offline, fragmentiert und nicht nachvollziehbar.",
      "Keine Transparenz hinsichtlich der Performance des Verschreibungs-zu-Konversions-Funnels",
      "CRM-, E-Commerce- und Apothekenkanäle arbeiteten isoliert voneinander.",
      "Regulatorische Vorgaben (DSGVO) schränkten die Möglichkeiten zur Verfolgung und Optimierung des Nutzerverhaltens ein.",
      "Dies führte zu Folgendem:",
      "Verpasste Konversionsmöglichkeiten",
      "Ineffiziente Marketinginvestitionen",
      "Es gibt keine Rückkopplungsschleife zwischen medizinischer Empfehlung und kommerziellem Ergebnis.",
      "LÖSUNG",
      "ein vollständig integriertes, DSGVO-konformes 360°-Ökosystem für elektronische Rezepte entwickelt, um Ärzte, Patienten, Apotheken und digitale Kanäle zu einem einzigen messbaren Prozess zu verbinden.",
      "Ich habe ein dynamisches Verschreibungssystem entwickelt , das personalisierte Produktempfehlungen generiert.",
      "Rezepte werden Patienten sofort über NFC-gesteuerte mobile Abläufe zugestellt.",
      "Verknüpfung der Rezeptausgabe mit E-Commerce- und Apotheken-Konversionsprozessen",
      "Die anonymisierte Datenerfassung wurde aktiviert , um die vollständige Einhaltung der Datenschutzbestimmungen zu gewährleisten.",
      "Es wurde ein geschlossenes System geschaffen , das die medizinische Absicht mit der kommerziellen Leistung verknüpft.",
      "AKTION",
      "Entwicklung einer durchgängigen digitalen Prozessarchitektur für den Rezeptierungsprozess (Arzt → Patient → Kauf)",
      "Entwicklung von NFC-fähigen Rezeptauslösern zur Beseitigung von Reibungsverlusten beim Zugriff",
      "Dynamische Empfehlungslogik basierend auf Indikations- und Produktzuordnung entwickelt",
      "Integriertes System mit E-Commerce-Plattformen und Apothekenabläufen",
      "Implementierte anonymisierte Tracking-Infrastruktur für DSGVO-konforme Messungen",
      "Erstellung von 360°-Funnel-Dashboards zur Überwachung von Verschreibung → Engagement → Konversion",
      "Ausrichtung der medizinischen, Marketing- und Vertriebsteams auf ein gemeinsames Leistungsmodell",
      "ERGEBNIS",
      "Umwandlung von Rezepten in Käufe: ~22 % → ~34 % (+12 Prozentpunkte)",
      "Arztadoptionsrate: +40%",
      "Abschluss des Apotheken-Funnels: +25 %",
      "Patientenbeteiligungsrate: +30%",
      "Steigerung der Kampagnenkonversion: +15 % durch vernetzte Customer Journeys",
      "Papierbasierte Betriebskosten: -70 % durch Digitalisierung",
      "Vollständige Transparenz des gesamten Verkaufsprozesses von der Rezeptabsicht bis zum endgültigen Kauf",
      "Dieses System hat die Verschreibung von Grund auf von einer statischen medizinischen Empfehlung in einen messbaren, optimierbaren Wachstumsmotor verwandelt .",
      "Es schuf erstmals eine Datenbrücke zwischen medizinischer Interaktion und kommerzieller Leistung und ermöglichte Folgendes:",
      "Intelligentere Budgetverteilung",
      "Echtzeit-Reiseoptimierung",
      "Stärkere Abstimmung zwischen medizinischer Strategie und Umsatzergebnissen",
      "BIODERMA soll nicht nur als Produktmarke, sondern als Akteur im digital vernetzten Ökosystem des Gesundheitswesens positioniert werden ."
    ],
    "BIODERMA AI-Driven Visit Planning Mobile Application": [
      "PROBLEM",
      "Die Planung der Außendienstbesuche erfolgte größtenteils manuell, statisch und nicht auf den kommerziellen Nutzen ausgerichtet.",
      "Die Besuchspläne basierten auf Gewohnheit, Gebietsnähe oder Intuition , nicht auf Daten.",
      "Es gibt keine strukturierte Methode zur Priorisierung von hochqualifizierten Gesundheitsfachkräften (CLV-basiert).",
      "Die Routen waren ineffizient, was zu Zeitverlusten und suboptimaler Abdeckung führte.",
      "Bisherige Erfahrungen und Potenziale im Bereich Engagement wurden nicht vollständig in die Planung einbezogen.",
      "Die Tagesplanung ließ es an Echtzeit-Anpassungsfähigkeit (Verkehr, Ausfälle, Änderungen) mangeln.",
      "Dies führte zu Folgendem:",
      "Geringe Feldproduktivität",
      "Verpasste, wertvolle Chancen",
      "Ineffiziente Zeitverteilung auf verschiedene Konten",
      "LÖSUNG",
      "Zur Optimierung der Außendiensttätigkeiten wurde ein KI-gestütztes mobiles Besuchsplanungs- und Entscheidungsunterstützungssystem entwickelt.",
      "Einführung eines CLV-basierten Priorisierungsmodells zur Rangfolge der HCPs nach Wert",
      "Entwicklung eines Systems zur Bewertung des Engagements unter Einbeziehung von Verhaltens- und Interaktionsdaten",
      "Integrierte Echtzeit-Verkehrsdaten zur dynamischen Optimierung der Routen",
      "Ermöglichte intelligente Kalenderplanung basierend auf Wert, Ort und Zeit",
      "Alle Erkenntnisse wurden über eine mobile Benutzeroberfläche für den Außeneinsatz bereitgestellt.",
      "AKTION",
      "Entwicklung und Implementierung von CLV/LTV-basierten Bewertungsmodellen zur Priorisierung von medizinischem Fachpersonal",
      "Entwicklung einer Logik zur Bewertung des Engagements unter Einbeziehung der Besuchshistorie und Interaktionssignale",
      "Entwicklung einer Routenoptimierungs-Engine zur Integration von Echtzeit-Verkehrs- und Geodaten",
      "Dynamische Tagesplanungsschnittstelle für mobile Nutzung erstellt",
      "Integration mit CRM und Datenquellen zur Sicherstellung eines Echtzeit-Datenflusses",
      "Die statische Planung wurde durch eine KI-gestützte Empfehlungsmaschine ersetzt.",
      "Geschulte Außendienstteams und Integration des Systems in die täglichen Arbeitsabläufe.",
      "ERGEBNIS",
      "Feldproduktivität: +25–30 % durch optimierte Besuchsplanung",
      "Abdeckung von Premium-Konten: +35 % durch CLV-basierte Priorisierung",
      "Routeneffizienz: +20 % (reduzierte Reisezeit und bessere Routenführung)",
      "Besuchseffektivität: +15–20 % (bessere Interaktionsqualität)",
      "Planungszeit: -40 % durch Automatisierung",
      "Akzeptanzrate (Außendienstteams): >80 % aufgrund der mobilen Benutzerfreundlichkeit",
      "Diese Lösung wandelte die Außendiensttätigkeit von einer statischen Planungsaktivität in ein KI-gestütztes Echtzeit-Entscheidungssystem um .",
      "Es ermöglichte einen Wechsel von:",
      "„Wer ist am nächsten dran?“ → „Wer schafft den größten Wert?“",
      "„Wohin soll ich gehen?“ → „Was ist heute die optimale Geschäftsroute?“",
      "Letztendlich geht es darum, den Außendienst als datengetriebenen Wachstumsmotor zu positionieren , nicht nur als Ausführungsebene."
    ],
    "BIODERMA Tasky AI Web Application": [
      "PROBLEM",
      "Die funktionsübergreifende Umsetzung zwischen den Teams aus Marketing, Vertrieb, Medizin und Handel war fragmentiert und schwer skalierbar.",
      "E-Mails, Meetings und nicht zusammenhängende Tools hinweg verwaltet.",
      "Eingeschränkte Transparenz darüber , wem was bis wann und in welchem Status gehört.",
      "Abhängigkeiten zwischen den Teams führten zu Engpässen und Verzögerungen.",
      "Keine standardisierte Workflow-Struktur → inkonsistente Ausführungsqualität",
      "Fehlende zentrale Kontrollmechanismen führten zu Unklarheiten hinsichtlich Leistung und Verantwortlichkeit.",
      "Dies führte zu Folgendem:",
      "Koordinationsprobleme zwischen den Teams",
      "Verzögerte Projektabwicklung",
      "Ineffiziente Nutzung von Ressourcen und Zeit",
      "LÖSUNG",
      "Zur Standardisierung der Ausführung und Verbesserung der funktionsübergreifenden Zusammenarbeit wurde ein zentralisiertes, KI-gestütztes Workflow- und Aufgabenmanagementsystem entwickelt.",
      "Ich habe ein individuelles Betriebsmodell entwickelt , das von Tools wie Wrike und Asana inspiriert ist.",
      "Etablierte, strukturierte Aufgabenabläufe, Verantwortlichkeiten und Fristverfolgung",
      "Ermöglichte teamübergreifende Transparenz über alle laufenden Projekte hinweg",
      "Einführung von KI-gestützter Priorisierung und Workflow-Steuerung",
      "Es wurde ein skalierbares System geschaffen, das auf die Organisationsprozesse und die Governance abgestimmt ist.",
      "AKTION",
      "Workflow-Architektur über alle Abteilungen hinweg",
      "Entwicklung einer individuellen Webanwendung unter Verwendung von Low-Code-Technologien (Power Apps-Ökosystem).",
      "Definierte standardisierte Aufgabenstrukturen (Verantwortlicher, Frist, Status, Abhängigkeiten)",
      "Implementierte funktionsübergreifende Projekt-Tracking-Dashboards",
      "Integrierte Arbeitsabläufe über Marketing-, Vertriebs- und Medizin-Teams hinweg",
      "Es wurden Benachrichtigungs- und Nachverfolgungsmechanismen eingeführt , um Verzögerungen zu reduzieren.",
      "Schulungen und eine entsprechende Governance-Anpassung in den täglichen Betrieb integriert.",
      "ERGEBNIS",
      "Ausführungsgeschwindigkeit: +30–40 % durch reduzierte Koordinationsreibung",
      "Aufgabentransparenz: +50 % über alle Teams und Stakeholder hinweg",
      "Pünktliche Lieferquote: +25 % durch strukturierte Sendungsverfolgung",
      "Funktionsübergreifende Abstimmung: +35 % (weniger Missverständnisse und Nacharbeiten)",
      "Manueller Nachbearbeitungsaufwand: -40 % durch automatisierte Nachverfolgung",
      "Operative Effizienz: +20–25 % teamübergreifend",
      "Diese Lösung wandelte die Ausführung von einem personenabhängigen Koordinationsmodell in ein systemgesteuertes Betriebsmodell um .",
      "Es ermöglichte einen Wechsel von:",
      "„Wer macht das?“ → „Es wird bereits erfasst, ist sichtbar und nachvollziehbar.“",
      "„Wie ist der aktuelle Stand?“ → „Alles ist in Echtzeit messbar.“",
      "Tasky AI positioniert sich als digitale Betriebssystemschicht, die Ausführungsqualität, Geschwindigkeit und organisatorische Disziplin skaliert."
    ],
    "360? Real-Time Executive Dashboard and Forecast": [
      "PROBLEM",
      "Die Entscheidungen im Bereich Handel und Lieferkette basierten auf verzögerten, fragmentierten und rückwärtsgewandten Daten.",
      "Abverkaufsdaten, Lagerbestände und Kampagnenleistung waren nicht einheitlich.",
      "Die Berichterstattung hinkte hinterher , wodurch es unmöglich war, in Echtzeit auf Nachfrageänderungen zu reagieren.",
      "Die Prognosen stützten sich stark auf manuelle Annahmen und statische Modelle.",
      "Begrenzte Transparenz hinsichtlich Saisonalitätsmustern und Trenddynamiken",
      "die Geschäftsentwicklung mit der Lagerplanung verknüpft .",
      "Dies führte zu Folgendem:",
      "Lagerungleichgewichte (Überbestand / Fehlbestände)",
      "Verpasste Umsatzchancen",
      "Reaktive statt proaktive Entscheidungsfindung",
      "LÖSUNG",
      "eine zentrale, in Echtzeit steuerbare Entscheidungsebene für das Management entwickelt, die Analytik, Prognosen und Business Intelligence in einem System vereint.",
      "Integrierte Abverkaufssignale, Kampagnendaten und Inventareingaben",
      "Erstellung von Vorhersagemodellen unter Verwendung von Saisonalität, historischen Trends und Nachfragesignalen",
      "Ermöglichte die Echtzeitüberwachung von Leistungs- und Nachfrageänderungen",
      "Es wurde eine einheitliche Management-Dashboard-Ebene für die Entscheidungsfindung geschaffen.",
      "Verknüpfung von kommerziellen und Lieferkettenperspektiven in einer einzigen Sichtweise",
      "AKTION",
      "Entwicklung und Implementierung von Datenpipelines zur Aggregation von Eingaben aus verschiedenen Quellen (Abverkauf, Lagerbestand, Medien, CRM)",
      "Entwicklung von prädiktiven Prognosemodellen, die Trend, Saisonalität und Echtzeitsignale kombinieren",
      "Entwicklung von Power BI-Dashboards für optimale Transparenz und Benutzerfreundlichkeit auf Führungsebene",
      "Leistungsverfolgung auf SKU- und Kategorieebene erstellt",
      "Implementierte Szenarioplanungsfunktionen für eine proaktive Entscheidungsfindung",
      "Echtzeitwarnungen und Anomalieerkennung bei Nachfrageverschiebungen aktiviert",
      "Ausgerichtete Stakeholder (Vertrieb, Lieferkette, Marketing) um eine einzige Entscheidungsschnittstelle",
      "ERGEBNIS",
      "Prognosegenauigkeit: +25–30 % durch prädiktive Modellierung",
      "Bestandsengpässe reduzieren: -20–25 % durch proaktive Planung",
      "Lagereffizienz: +15–20 % (bessere Lagerallokation)",
      "Entscheidungsgeschwindigkeit: +50 % durch Echtzeit-Sichtbarkeit",
      "Umsatzpotenzialausschöpfung: +10–15 % durch Nachfrageorientierung",
      "Transparenz für Führungskräfte: +100 % (einheitliche Informationsquelle über alle Funktionen hinweg)",
      "Dieses System wandelte das Reporting von einer passiven Analysefunktion in eine aktive Entscheidungsmaschine um .",
      "Es ermöglichte einen Wechsel von:",
      "„Was ist passiert?“ → „Was wird als Nächstes passieren?“",
      "„Lass uns das später analysieren“ → „Lass uns jetzt handeln“",
      "Das Dashboard wird nicht als reines Berichtsinstrument positioniert, sondern als Echtzeit-Kontrollturm für den kommerziellen Bereich, der die Prognosegenauigkeit, die Lagereffizienz und die Geschäftsleistung optimiert."
    ],
    "BIODERMA Invoice Automation System": [
      "PROBLEM",
      "Die Rechnungsverarbeitung erfolgte manuell, war repetitiv und fehleranfällig, was zu Ineffizienzen im Finanzbereich führte.",
      "Die Rechnungen trafen als E-Mail-Anhang in verschiedenen Formaten ein (PDF, Bild, Scan).",
      "Die Datenextraktion erforderte manuelles Ablesen und Eingeben in Systeme.",
      "Hohes Risiko menschlicher Fehler und Inkonsistenzen",
      "Keine zentrale Struktur für die Suche, Verfolgung oder Validierung von Rechnungen",
      "Erheblicher Zeitaufwand für geringwertige, sich wiederholende Aufgaben",
      "Dies führte zu Folgendem:",
      "Operative Engpässe in Finanzprozessen",
      "Begrenzte Datenzuverlässigkeit",
      "Geringe Skalierbarkeit bei steigendem Volumen",
      "LÖSUNG",
      "Mithilfe von OCR und Power Automate wurde ein automatisierter Workflow für die Rechnungserfassung und -verarbeitung entwickelt.",
      "Rechnungsdaten wurden automatisch aus E-Mail-Anhängen extrahiert.",
      "Anwendung von OCR-Technologie zum Lesen unstrukturierter Dokumente",
      "Die validierten Daten wurden in einer strukturierten, zentralen Dokumentenebene konsolidiert.",
      "Aktivierte durchsuchbare, nachverfolgbare und standardisierte Finanzeingaben",
      "Verringerte Abhängigkeit von manueller Bearbeitung und fragmentierten Prozessen",
      "AKTION",
      "Entwurf und Implementierung einer Power Automate-Workflow-Architektur",
      "Integrierte E-Mail-Erfassungsauslöser zur automatischen Rechnungserkennung",
      "Entwicklung einer OCR-basierten Extraktionspipeline zur Erfassung strukturierter Daten",
      "Definierte Validierungslogik zur Sicherstellung der Datengenauigkeit und -konsistenz",
      "Rechnungsarchiv / operative Dokumentenebene erstellt",
      "Standardisierte Datenfelder für die Benutzerfreundlichkeit im Finanz- und Berichtswesen",
      "Automatisierte Routenplanung und -abwicklung zur Vermeidung manueller Eingriffe",
      "ERGEBNIS",
      "Manueller Bearbeitungsaufwand: -60–70 % durch Automatisierung",
      "Bearbeitungszeit pro Rechnung: -50%",
      "Datengenauigkeit: +25–30 % durch standardisierte Extraktion",
      "Operativer Arbeitsaufwand: deutlich reduziert , wodurch finanzielle Ressourcen freigesetzt werden",
      "Suchbarkeit und Nachverfolgbarkeit: +100 % mit zentralisierter Datenstruktur",
      "Skalierbarkeit: ohne Erhöhung der Mitarbeiterzahl möglich.",
      "Dieses System wandelte die Rechnungsbearbeitung von einer manuellen Backoffice-Aufgabe in eine strukturierte, automatisierte Datenpipeline um .",
      "Es ermöglichte einen Wechsel von:",
      "„Öffnen, lesen, eingeben“ → „Automatisch erfassen, validieren, speichern“",
      "„Wo ist diese Rechnung?“ → „Alles ist durchsuchbar und strukturiert.“",
      "Positionierung der Finanzprozesse als datengesteuerte und automatisierungsfähige Funktion , nicht als manuelle Verarbeitungsschicht."
    ],
    "BIODERMA PTA Challenge Web Application": [
      "PROBLEM",
      "Die Aktivierungskampagnen für den Apothekenvertrieb waren schwer zu verfolgen, zu validieren und zu skalieren.",
      "Die Vertriebsbeteiligung basierte auf manuellen Meldungen oder vertrauensbasierten Eingaben.",
      "Es gibt keine zuverlässige Methode, die tatsächliche Verkaufsleistung auf Produktebene zu überprüfen.",
      "Eingeschränkte Transparenz darüber , wer wie viel und wie schnell Leistung erbringt.",
      "Den Anreizprogrammen mangelte es an Transparenz und Echtzeitmotivation.",
      "Für die Kampagnenverfolgung war eine manuelle Konsolidierung und Abstimmung erforderlich.",
      "Dies führte zu Folgendem:",
      "Geringes Engagement der Apothekenteams",
      "Ineffiziente Kampagnendurchführung",
      "Begrenzte Fähigkeit zur Optimierung der leistungsorientierten Vertriebsleistung",
      "LÖSUNG",
      "eine spielerische, webbasierte Apotheken-Wettbewerbsplattform entwickelt, die eine OCR-basierte Verkaufsvalidierung mit einer Echtzeit-Ranglistenverfolgung kombiniert.",
      "Ermöglichte es Apotheken, Belege zu scannen und Verkaufsnachweise digital einzureichen.",
      "Mithilfe von OCR wurden Produktdaten, Mengen und Preise von BIODERMA extrahiert.",
      "Verknüpfung von Einreichungen mit Teilnehmerkonten und Kampagnenlogik",
      "Einführung eines Echtzeit-Ranglistensystems zur Förderung von Wettbewerb und Engagement",
      "Es wurde ein transparentes, skalierbares System für anreizbasierte Verkaufsaktivierung geschaffen.",
      "AKTION",
      "Entwicklung einer durchgängigen Architektur für ein Herausforderungs- und Belohnungssystem",
      "Entwicklung einer OCR-Pipeline zur Extraktion von Produktdaten aus Belegbildern",
      "Entwickelte Validierungslogik , um die Genauigkeit der übermittelten Verkaufsdaten sicherzustellen.",
      "Entwicklung einer Benutzeroberfläche für Apotheken zum Hochladen und Verfolgen von Einreichungen.",
      "Echtzeit-Rangliste und Punktesystem implementiert",
      "Integriertes Kampagnen-Tracking für Marketing- und Vertriebsteams",
      "Automatisierte Zusammenführung von Verkaufsdaten für Leistungsüberwachung und Berichterstattung",
      "ERGEBNIS",
      "Apotheken-Engagement: +40–50 % durch spielerische Teilnahme",
      "Verkaufsaktivierungsleistung: +20–30 % Steigerung während der Kampagnenzeiträume",
      "Datenzuverlässigkeit: +30 % durch OCR-basierte Validierung",
      "Aufwand für Kampagnen-Tracking: -50 % durch Automatisierung",
      "Transparenz: +100 % dank Echtzeit-Ranglistenansicht",
      "Teilnahmequote: im gesamten Apothekennetzwerk deutlich erhöht.",
      "Diese Lösung hat Incentive-Kampagnen von einem manuellen, intransparenten Prozess in ein datengesteuertes Echtzeit-Engagement-System verwandelt .",
      "Es ermöglichte einen Wechsel von:",
      "„Melden Sie Ihre Verkäufe“ → „Beweisen und verfolgen Sie sie sofort“",
      "„Wer tritt auf?“ → „Verfolge es live auf der Rangliste“",
      "Die Plattform positioniert sich als skalierbare Vertriebsaktivierungsmaschine , die Gamifizierung, Validierung und Leistungstransparenz in einem System vereint."
    ]
  },
  "tr": {
    "Pricing Validation & Intelligence": [
      "SORUN",
      "E-ticaret siteleri ve pazar yerlerindeki fiyatlandırma kararları oldukça parçalı ve tepkiseldi.",
      "Perakendeci fiyat verileri, rakip kıyaslamaları ve şirket içi fiyatlandırma mantığı birbirinden kopuktu.",
      "Fiyatlandırma uyumluluğu (tavsiye edilen perakende satış fiyatı, kar marjı eşikleri) tutarlı bir şekilde uygulanamadı.",
      ", Excel tabanlı manuel karşılaştırmalara güveniyorlardı ; bu da gecikmelere ve hatalara yol açıyordu.",
      "Sınırlı görünürlük, gri market risklerine, fiyat çatışmalarına ve kar marjı kaybına yol açtı.",
      "Karar alma süreci yavaş, tutarsız ve kanallar genelinde ölçeklenebilir değildi.",
      "ÇÖZÜM",
      "yapay zeka destekli birleşik bir fiyatlandırma zekası katmanı geliştirildi.",
      "Bağlantılı PIM verileri, perakendeci fiyat akışları ve rakip verileri",
      "Normalleştirilmiş kıyaslama için yapay zeka tabanlı ürün eşleştirme uygulandı .",
      "Belirlenmiş fiyatlandırma güvenlik önlemleri (Önerilen perakende satış fiyatı, kar marjı eşikleri, kanal stratejisi)",
      "Periyodik kontroller yerine gerçek zamanlı bir doğrulama ve izleme sistemi kurduk.",
      "Merkezi kontrol panelleri aracılığıyla kar marjı bilincine sahip ve rekabetçi fiyatlandırma kararları alınmasını sağladı .",
      "AKSİYON",
      "Dahili ve harici fiyatlandırma sinyallerini birleştiren veri mimarisini tasarladım ve uyguladım.",
      "Perakendeci ve rakip verilerini alıp normalleştirmek için otomatik veri işleme hatları oluşturuldu.",
      "Fiyat sapmalarını ve riskleri belirlemek için yapay zeka destekli doğrulama mantığı geliştirildi.",
      "Ürün bazında gerçek zamanlı görünürlük için kıyaslama ve fiyatlandırma panoları oluşturuldu.",
      "Manuel raporlamanın yerini alacak ve uygulama sürecini hızlandıracak karar verme iş akışları tanıtıldı.",
      "Pazarlama, satış ve ticari ekipleri tek bir güvenilir fiyatlandırma kaynağı etrafında birleştirmek.",
      "SONUÇ",
      "Optimize edilmiş fiyatlandırma stratejileri sayesinde Ortalama Sipariş Değerinde (AOV) %11 artış",
      "Rekabet gücünün ve fiyat tutarlılığının artmasıyla %12'lik bir alım payı artışı sağlandı.",
      "Kâr marjını dikkate alan fiyatlandırma kararlarının uygulanmasıyla +14pp katkı marjı.",
      "Otomatik güvenlik bariyeri denetimi ile %30'dan fazla fiyat uyumluluk oranı.",
      "Excel tabanlı iş akışlarının ortadan kaldırılmasıyla manuel fiyatlandırma çabasında %40 azalma sağlandı.",
      "Gerçek zamanlı veriler sayesinde %50 daha hızlı karar verme",
      "+%25 Kanallar Arası Fiyat Tutarlılığı, marka ve kanal kontrolünü iyileştiriyor"
    ],
    "BIODERMA 360 e-Prescription System": [
      "SORUN",
      "Sağlık hizmetleri ve dermokozmetik yolculukları, reçete yazma niyeti ile gerçek satın alma davranışı arasında temel bir kopukluk gösteriyordu.",
      "Doktorlar tavsiyelerde bulundu, ancak reçete ile satın alma arasında ölçülebilir bir bağlantı yoktu.",
      "Hastaların tedavi süreçleri öncelikle çevrimdışıydı, parçalıydı ve izlenemiyordu.",
      "Reçeteden dönüşüme kadar olan süreç performansına dair hiçbir görünürlük yok.",
      "CRM, e-ticaret ve eczane kanalları birbirinden bağımsız olarak faaliyet gösteriyordu.",
      "Genel Veri Koruma Yönetmeliği (GDPR) gibi yasal kısıtlamalar, kullanıcı davranışını izleme ve optimize etme yeteneğini sınırladı.",
      "Bu durum şu sonuçlara yol açtı:",
      "Kayıp dönüşüm fırsatları",
      "Verimsiz pazarlama yatırımları",
      "Tıbbi öneri ile ticari sonuç arasında sıfır geri bildirim döngüsü",
      "ÇÖZÜM",
      ", tamamen entegre 360° e-reçete ekosistemi tasarlandı.",
      "Kişiselleştirilmiş ürün önerileri üreten dinamik bir reçete sistemi geliştirdim.",
      "NFC ile tetiklenen mobil akışlar aracılığıyla reçeteler hastalara anında ulaştırıldı.",
      "e-ticaret ve eczane dönüşüm süreçlerine bağlamak",
      "Gizlilik düzenlemelerine tam uyumluluğu sağlamak için anonimleştirilmiş veri yakalama özelliği etkinleştirildi .",
      "Tıbbi amacı ticari performansla ilişkilendiren kapalı döngü bir sistem oluşturuldu.",
      "AKSİYON",
      "Dijital reçete sürecinin baştan sona mimarisini tasarladım (doktor → hasta → satın alma).",
      "Erişimdeki engelleri ortadan kaldırmak için NFC özellikli reçete tetikleyicileri geliştirildi .",
      "Endikasyon ve ürün eşleştirmesine dayalı dinamik öneri mantığı oluşturuldu.",
      "E-ticaret platformları ve eczane süreçleriyle entegre sistem",
      "GDPR uyumlu ölçüm için anonimleştirilmiş izleme altyapısı uygulandı.",
      "Reçete yazımından etkileşime ve dönüşüme kadar olan süreci izlemek için 360° dönüşüm hunisi panoları oluşturuldu .",
      "Tıbbi, pazarlama ve ticari ekipleri ortak bir performans modeli etrafında bir araya getirmek.",
      "SONUÇ",
      "Reçeteden satın almaya dönüşüm oranı: ~%22 → ~%34 (+12 puan)",
      "Doktor benimseme oranı: +%40",
      "Eczane satış hunisi tamamlanma oranı: +%25",
      "Hasta katılım oranı: +%30",
      "Bağlantılı müşteri yolculukları sayesinde kampanya dönüşüm oranında %15 artış.",
      "Kağıt tabanlı işletme giderlerinde: Dijitalleşme sayesinde %70 azalma.",
      "Reçete yazma niyeti aşamasından nihai satın alma aşamasına kadar tüm süreç boyunca görünürlük.",
      "Bu sistem, reçete yazımını statik bir tıbbi öneriden ölçülebilir, optimize edilebilir bir büyüme motoruna dönüştürdü .",
      "Bu, ilk kez tıbbi etkileşim ile ticari performans arasında bir veri köprüsü kurarak şunları mümkün kıldı:",
      "Daha akıllı bütçe tahsisi",
      "Gerçek zamanlı yolculuk optimizasyonu",
      "Tıbbi strateji ve gelir sonuçları arasında daha güçlü bir uyum",
      "BIODERMA'yı sadece bir ürün markası olarak değil, dijital olarak desteklenen bir sağlık hizmetleri ekosistemi oyuncusu olarak konumlandırmak ."
    ],
    "BIODERMA AI-Driven Visit Planning Mobile Application": [
      "SORUN",
      "Saha ekibi ziyaret planlaması büyük ölçüde manuel, statik ve ticari değerle uyumlu değildi.",
      "verilere değil, alışkanlığa, bölgeye yakınlığa veya sezgiye dayanıyordu .",
      "Yüksek değerli sağlık profesyonellerini (CLV tabanlı) önceliklendirmek için yapılandırılmış bir yöntem yok.",
      "Rotalar verimsizdi, bu da zaman kaybına ve yetersiz kapsama alanına yol açıyordu.",
      "Geçmişe yönelik etkileşim ve potansiyel, planlamaya tam olarak entegre edilmedi.",
      "Günlük planlamada gerçek zamanlı uyarlanabilirlik (trafik, iptaller, değişiklikler) eksikliği vardı.",
      "Bu durum şu sonuçlara yol açtı:",
      "Düşük tarla verimliliği",
      "Kaçırılan yüksek değerli fırsatlar",
      "Hesaplar arasında verimsiz zaman tahsisi",
      "ÇÖZÜM",
      "yapay zeka destekli bir mobil ziyaret planlama ve karar destek sistemi geliştirildi.",
      "Sağlık çalışanlarını değerlerine göre sıralamak için CLV tabanlı önceliklendirme modeli tanıtıldı .",
      "Davranışsal ve etkileşim verilerini birleştiren bir katılım puanlama sistemi oluşturuldu.",
      "Rota optimizasyonu için entegre edilmiş gerçek zamanlı trafik verileri.",
      "Değer, konum ve zamanlamaya dayalı akıllı takvim planlaması etkinleştirildi.",
      "Tüm veriler, saha kullanımını kolaylaştırmak amacıyla mobil öncelikli bir arayüz üzerinden sunuldu.",
      "AKSİYON",
      "Sağlık profesyonellerinin önceliklendirilmesi için CLV/LTV tabanlı puanlama modelleri tasarlandı ve uygulandı.",
      "Ziyaret geçmişi ve etkileşim sinyallerini içeren geliştirilmiş etkileşim puanlama mantığı.",
      "Gerçek zamanlı trafik ve coğrafi verileri entegre eden rota optimizasyon motoru geliştirildi.",
      "Mobil kullanım için dinamik günlük planlama arayüzü oluşturuldu.",
      "Gerçek zamanlı veri akışını sağlamak için CRM ve veri kaynakları ile entegre edilmiştir.",
      "Statik planlama, yapay zeka destekli öneri motoruyla değiştirildi.",
      "Saha ekiplerini eğittik ve sistemi günlük iş akışlarına entegre ettik.",
      "SONUÇ",
      "Optimize edilmiş ziyaret planlaması sayesinde +%25-30",
      "Yüksek değerli müşteri kapsamı: Müşteri yaşam değeri (CLV) tabanlı önceliklendirme yoluyla +%35",
      "Rota verimliliği: +%20 (azaltılmış seyahat süresi ve daha iyi sıralama)",
      "Ziyaret etkinliği: +%15-20 (daha kaliteli etkileşimler)",
      "Planlama süresi: Otomasyon sayesinde %40 azalma",
      "Benimseme oranı (saha ekipleri): Mobil öncelikli kullanılabilirlik sayesinde %80'in üzerinde.",
      "Bu çözüm, saha operasyonlarını statik bir planlama faaliyetinden gerçek zamanlı, yapay zeka destekli bir karar sistemine dönüştürdü.",
      "Bu, şu durumlara geçişi mümkün kıldı:",
      "“En yakın kim?” → “En çok değeri kim yaratıyor?”",
      "“Nereye gitmeliyim?” → “Bugün en uygun ticari rota hangisi?”",
      "Sonuç olarak, saha ekibini sadece bir uygulama katmanı olarak değil, veri odaklı bir büyüme motoru olarak konumlandırmak."
    ],
    "BIODERMA Tasky AI Web Application": [
      "SORUN",
      "Pazarlama, Satış, Tıbbi ve Ticari ekipler arasında çapraz fonksiyonel uygulama parçalıydı ve ölçeklendirilmesi zordu.",
      "e-postalar, toplantılar ve birbirinden bağımsız araçlar aracılığıyla yönetildi.",
      "Kimin neye, ne zamana kadar ve hangi statüde sahip olduğuna dair sınırlı görünürlük.",
      "Ekipler arasındaki bağımlılıklar darboğazlara ve gecikmelere yol açtı.",
      "Standartlaştırılmış iş akışı yapısı yok → tutarsız uygulama kalitesi",
      "Merkezi takip sisteminin olmaması, performans ve hesap verebilirliğin belirsizleşmesine neden oldu.",
      "Bu durum şu sonuçlara yol açtı:",
      "Ekipler arası koordinasyon sorunları",
      "Proje tesliminde gecikme",
      "Kaynakların ve zamanın verimsiz kullanımı",
      "ÇÖZÜM",
      ", yapay zeka destekli merkezi bir iş akışı ve görev yönetim sistemi geliştirildi.",
      "Wrike ve Asana gibi araçlardan ilham alarak özel bir işletim modeli geliştirdim.",
      "Yapılandırılmış görev akışları, sorumluluk ve son tarih takibi oluşturuldu.",
      "Devam eden tüm projelerde ekipler arası görünürlük sağlandı .",
      "Yapay zeka destekli önceliklendirme ve iş akışı yönlendirme özelliği tanıtıldı.",
      "Kurumsal süreçler ve yönetişimle uyumlu, ölçeklenebilir bir sistem oluşturuldu.",
      "AKSİYON",
      "Departmanlar arası uçtan uca iş akışı mimarisi tasarlandı.",
      "Düşük kodlu teknolojileri (Power Apps ekosistemi) kullanarak özel bir web uygulaması geliştirdim.",
      "Tanımlanmış standartlaştırılmış görev yapıları (sahip, son tarih, durum, bağımlılıklar)",
      "Çeşitli departmanlar arası proje takip panoları uygulandı.",
      "Pazarlama, Satış ve Tıp ekipleri arasında entegre iş akışları",
      "Gecikmeleri azaltmak için bildirim ve takip mekanizmaları uygulamaya konuldu .",
      "Eğitim ve yönetimsel uyum yoluyla sistemin günlük operasyonlara entegre edilmesi.",
      "SONUÇ",
      "Yürütme hızı: Koordinasyon sürtünmesinin azaltılması sayesinde +%30-40 artış",
      "Ekipler ve paydaşlar genelinde %50 artış",
      "Zamanında teslimat oranı: Yapılandırılmış takip sayesinde +%25",
      "Fonksiyonlar arası uyum: +%35 (yanlış iletişim ve yeniden işleme ihtiyacında azalma)",
      "Manuel takip çabası: Otomatik takip sayesinde %40 azaldı.",
      "Operasyonel verimlilik: Ekipler genelinde +%20-25",
      "Bu çözüm, uygulama sürecini insan odaklı koordinasyon modelinden sistem odaklı bir işletme modeline dönüştürdü .",
      "Bu, şu durumlara geçişi mümkün kıldı:",
      "“Bunu kim yapıyor?” → “Zaten takip ediliyor, görünür ve hesap verilebilir durumda.”",
      "“Durum nedir?” → “Her şey gerçek zamanlı olarak ölçülebilir.”",
      "Tasky AI'yı, uygulama kalitesini, hızı ve organizasyonel disiplini ölçeklendiren dijital bir işletim sistemi katmanı olarak konumlandırıyoruz."
    ],
    "360? Real-Time Executive Dashboard and Forecast": [
      "SORUN",
      "Ticari ve tedarik zinciri kararları gecikmeli, parçalı ve geçmişe dönük verilere dayanıyordu.",
      "Satış verileri, stok seviyeleri ve kampanya performansı birleştirilmemişti .",
      "Raporlama gecikmeli gerçekleştiği için , talep değişimlerine gerçek zamanlı olarak yanıt vermek imkansız hale geliyordu.",
      "manuel varsayımlara ve statik modellere dayanıyordu .",
      "Mevsimsellik kalıpları ve trend dinamikleri hakkında sınırlı bilgi sahibi olma",
      "Ticari performansı stok planlaması ile ilişkilendirecek tek bir sistem yok.",
      "Bu durum şu sonuçlara yol açtı:",
      "Stok dengesizlikleri (aşırı stok / stok yetersizliği)",
      "kaçırılan gelir fırsatları",
      "Proaktif karar alma yerine reaktif karar alma",
      "ÇÖZÜM",
      "merkezi ve gerçek zamanlı bir yönetici karar alma katmanı geliştirildi.",
      "Entegre satış sinyalleri, kampanya verileri ve stok girdileri",
      "Mevsimsellik, geçmiş trendler ve talep sinyallerini kullanarak tahmine dayalı modeller oluşturuldu.",
      "Performans ve talep değişimlerinin gerçek zamanlı olarak izlenmesini sağladı.",
      "Karar verme süreçleri için birleşik bir yönetici kontrol paneli katmanı oluşturuldu.",
      "Ticari ve tedarik zinciri perspektiflerini tek bir görünümde birleştirme",
      "AKSİYON",
      "Çok kaynaklı verileri (satış, stok, medya, CRM) bir araya getiren veri işlem hatları tasarladım ve uyguladım.",
      "Trend, mevsimsellik ve gerçek zamanlı sinyalleri birleştiren öngörücü modeller geliştirildi.",
      "Üst düzey yöneticiler için görünürlük ve kullanım kolaylığı sağlayan Power BI panoları geliştirdim.",
      "Ürün kodu (SKU) ve kategori düzeyinde performans takibi oluşturuldu.",
      "Proaktif karar alma için senaryo planlama yetenekleri uygulandı .",
      "Talep değişimleri için gerçek zamanlı uyarı ve anormallik tespiti etkinleştirildi.",
      "Paydaşların (Ticari, Tedarik Zinciri, Pazarlama) tek bir karar arayüzü etrafında bir araya getirilmesi.",
      "SONUÇ",
      "Tahmin doğruluğu: Tahmin modellemesi yoluyla +%25-30 artış",
      "Stok tükenme oranında azalma: Proaktif planlama yoluyla %20-25 oranında düşüş.",
      "Stok verimliliği: +%15-20 (daha iyi stok dağılımı)",
      "Karar alma hızı: Gerçek zamanlı görünürlükle %50 artış",
      "Talep yanıtı yoluyla %10-15 artış",
      "Üst düzey yöneticiler için görünürlük: +%100 (tüm fonksiyonlarda tek doğru bilgi kaynağı)",
      "Bu sistem, raporlamayı pasif bir analiz işlevinden aktif bir karar alma motoruna dönüştürdü .",
      "Bu, şu durumlara geçişi mümkün kıldı:",
      "“Ne oldu?” → “Bundan sonra ne olacak?”",
      "“Analizini sonra yapalım” → “Şimdi harekete geçelim”",
      "Kontrol panelini bir raporlama aracı olarak değil, tahmin doğruluğunu, envanter verimliliğini ve iş performansını yönlendiren gerçek zamanlı bir ticari kontrol kulesi olarak konumlandırmak."
    ],
    "BIODERMA Invoice Automation System": [
      "SORUN",
      "Faturaların işlenmesi manuel, tekrarlayan ve hataya açık bir süreçti; bu da finans operasyonlarında verimsizliğe yol açıyordu.",
      "e-posta eki olarak farklı formatlarda (PDF, resim, tarama) geldi .",
      "Veri çıkarma işlemi manuel okuma ve sistemlere giriş gerektiriyordu.",
      "insan hatası ve tutarsızlık riski",
      "Faturaları aramak, izlemek veya doğrulamak için merkezi bir yapı yok.",
      "Değeri düşük, tekrarlayan görevlere önemli miktarda zaman harcanması",
      "Bu durum şu sonuçlara yol açtı:",
      "Finans iş akışlarındaki operasyonel darboğazlar",
      "Sınırlı veri güvenilirliği",
      "Hacim arttıkça ölçeklenebilirlik azaldı.",
      "ÇÖZÜM",
      "otomatik bir fatura alım ve işleme iş akışı geliştirildi.",
      "E-posta eklerinden fatura verileri otomatik olarak çıkarıldı.",
      "Yapılandırılmamış belgeleri okumak için OCR teknolojisi uygulandı.",
      "Doğrulanmış veriler, yapılandırılmış ve merkezi bir belge katmanında birleştirildi.",
      "Aranabilir, izlenebilir ve standartlaştırılmış finansal girdiler sağlandı .",
      "Elle işleme ve parçalı süreçlere olan bağımlılığın azaltılması",
      "AKSİYON",
      "Power Automate iş akışı mimarisini tasarladım ve uyguladım.",
      "Otomatik fatura tespiti için entegre e-posta alım tetikleyicileri",
      "Yapılandırılmış veri yakalama için OCR tabanlı veri çıkarma işlem hattı oluşturuldu.",
      "Veri doğruluğunu ve tutarlılığını sağlamak için tanımlanmış doğrulama mantığı.",
      "Merkezi fatura deposu / operasyonel belge katmanı oluşturuldu.",
      "Finans ve raporlama kullanım kolaylığı için standartlaştırılmış veri alanları",
      "Otomatik yönlendirme ve taşıma sayesinde manuel müdahale ortadan kalkar.",
      "SONUÇ",
      "Manuel işlem çabası: Otomasyon sayesinde %60-70 oranında azalma.",
      "Fatura başına işlem süresi: -%50",
      "Veri doğruluğu: Standartlaştırılmış ekstraksiyon yoluyla +%25-30",
      "Operasyonel iş yükü önemli ölçüde azaldı , böylece finans kaynakları serbest kaldı.",
      "Arama kolaylığı ve izlenebilirlik: Merkezi veri yapısıyla +%100 artış",
      "Ölçeklenebilirlik: Personel sayısını artırmadan mümkün",
      "Bu sistem, fatura işlemlerini manuel bir arka ofis görevinden yapılandırılmış, otomatikleştirilmiş bir veri akışına dönüştürdü .",
      "Bu, şu durumlara geçişi mümkün kıldı:",
      "“Aç, oku, gir” → “Otomatik olarak al, doğrula, sakla”",
      "“Bu fatura nerede?” → “Her şey aranabilir ve yapılandırılmış durumda”",
      "manuel işlem katmanı olarak değil, veri odaklı ve otomasyon destekli bir işlev olarak konumlandırmak ."
    ],
    "BIODERMA PTA Challenge Web Application": [
      "SORUN",
      "Eczane satış aktivasyon kampanyalarının izlenmesi, doğrulanması ve ölçeklendirilmesi zordu.",
      ", manuel raporlama veya güvene dayalı girdiler esas alınarak gerçekleştirilmiştir.",
      "Ürün bazında gerçek satış performansını doğrulamak için güvenilir bir yöntem bulunmamaktadır.",
      "Kimlerin performans sergilediği, ne kadar ve ne hızda performans sergilediği konusunda sınırlı görünürlük mevcuttur.",
      "Teşvik programlarında şeffaflık ve gerçek zamanlı motivasyon eksikliği vardı.",
      "Kampanya takibi manuel birleştirme ve mutabakat gerektiriyordu.",
      "Bu durum şu sonuçlara yol açtı:",
      "Eczane ekiplerinden düşük katılım",
      "Verimsiz kampanya yürütme",
      "Teşvik odaklı satış performansını optimize etme yeteneğinin sınırlı olması",
      "ÇÖZÜM",
      "web tabanlı bir eczane yarışması platformu geliştirildi.",
      "Eczanelerin fişleri tarayarak satış kanıtlarını dijital olarak göndermelerini sağladı.",
      "kullanılarak BIODERMA ürün verileri, miktarları ve fiyatları çıkarıldı.",
      "Katılımcı hesaplarına ve kampanya mantığına bağlı gönderiler.",
      "Rekabeti ve katılımı artırmak için gerçek zamanlı liderlik tablosu sistemi kullanıma sunuldu.",
      "Teşvik tabanlı satış aktivasyonu için şeffaf ve ölçeklenebilir bir sistem oluşturuldu.",
      "AKSİYON",
      "Uçtan uca tasarlanmış meydan okuma ve ödül sistemi mimarisi.",
      "Fiş görüntülerinden ürün düzeyinde verileri çıkarmak için OCR işlem hattı oluşturuldu .",
      "Gönderilen satış verilerinin doğruluğunu sağlamak için doğrulama mantığı geliştirildi .",
      "başvuruları yüklemesi ve takip etmesi için kullanıcı arayüzü oluşturuldu .",
      "Gerçek zamanlı sıralama tablosu ve puanlama sistemi uygulandı.",
      "Pazarlama ve Ticari ekipler için entegre kampanya takibi",
      "Performans izleme ve raporlama için satış verilerinin otomatik olarak toplanması",
      "SONUÇ",
      "Oyunlaştırılmış katılım yoluyla %40-50 artış",
      "Kampanya dönemlerinde %20-30 artış",
      "OCR tabanlı doğrulama yoluyla +%30 artış",
      "Kampanya takibi çabası: Otomasyon sayesinde %50 azalma.",
      "Gerçek zamanlı liderlik tablosu görünürlüğü ile +%100",
      "Katılım oranı: eczane ağı genelinde önemli ölçüde arttı.",
      "Bu çözüm, teşvik kampanyalarını manuel ve şeffaf olmayan bir süreçten gerçek zamanlı, veri odaklı bir etkileşim sistemine dönüştürdü .",
      "Bu, şu durumlara geçişi mümkün kıldı:",
      "“Satışlarınızı bildirin” → “Anında kanıtlayın ve takip edin”",
      "“Kim sahne alacak?” → “Skor tablosunda canlı olarak izleyin”",
      "Platformu , oyunlaştırma, doğrulama ve performans görünürlüğünü tek bir sistemde birleştiren, ölçeklenebilir bir satış aktivasyon motoru olarak konumlandırıyoruz."
    ]
  }
} as const;
